# Generated by Django 4.1.2 on 2022-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado_disponible',
            field=models.BooleanField(default=False),
        ),
    ]
