# Generated by Django 4.1.2 on 2022-10-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_item_estado_disponible2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado_disponible3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_disponible4',
            field=models.BooleanField(default=False),
        ),
    ]
